export function getEnv(key: string) {
  return process.env[key];
}

export enum EnvKey {
  ENV_UPDATE_AT = "ENV_UPDATE_AT",

  APP_ENVIRONMENT = "APP_ENVIRONMENT",
  APP_LISTEN_PORT = "APP_LISTEN_PORT",
  APP_LISTEN_HOST = "APP_LISTEN_HOST",
  APP_ACCESS_TOKEN = "APP_ACCESS_TOKEN",

  GOOGLE_CALENDAR_API_SERVICE_ACCOUNT_KEY_FILE_CONTENT = "GOOGLE_CALENDAR_API_SERVICE_ACCOUNT_KEY_FILE_CONTENT",

  OPENAI_API_KEY = "OPENAI_API_KEY",
}
