name: Build and Deploy

on:
  push:
    branches:
      - main
      - development

jobs:
  validate-commit-message:
    name: Validate Commit Message
    runs-on: ubuntu-latest
    outputs:
      commit_message: ${{ steps.check_commit_message.outputs.commit_message }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check commit message
        id: check_commit_message
        run: |
          commit_message=$(git log --format=%B -n 1 ${{ github.sha }})
          if [[ $commit_message =~ ^[0-9]+\.[0-9]+\.[0-9] ]]; then
            echo "commit_message=$commit_message" >> "$GITHUB_OUTPUT"
          fi

      - name: Generate GitHub summary
        if: always()
        run: |
          if [[ "${{ steps.check_commit_message.outputs.commit_message }}" != "" ]]; then
            echo "## :white_check_mark: Versioned push" >> $GITHUB_STEP_SUMMARY
            echo "Initiating Docker image build and push for version \`${{ steps.check_commit_message.outputs.commit_message }}\`." >> $GITHUB_STEP_SUMMARY
          else
            echo "## :x: This push does not qualify as a version push" >> $GITHUB_STEP_SUMMARY
            echo "Skipping the build and push process." >> $GITHUB_STEP_SUMMARY
          fi

  build-and-push:
    name: Build and Push Docker Image
    needs: [validate-commit-message]
    if: ${{ needs.validate-commit-message.outputs.commit_message != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure jq is installed
        run: |
          if ! command -v jq &> /dev/null; then
            echo "jq not found, installing jq..."
            sudo apt-get update
            sudo apt-get install -y jq
          else
            echo "jq is already installed"
          fi

      - name: Extract image name and version from package.json
        id: vars
        run: |
          IMAGE_NAME=$(jq -r '.name' package.json)
          IMAGE_VERSION=$(jq -r '.version' package.json)
          if [ "${{ github.ref }}" == "refs/heads/development" ]; then
            IMAGE_NAME="${IMAGE_NAME}-development"
          fi
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "IMAGE_VERSION=$IMAGE_VERSION" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set start time
        run: |
          echo "START_TIME=$(date +%s)" >> $GITHUB_ENV

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
            ${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Post-build summary
        run: |
          CURRENT_TIME=$(date +%s)
          ELAPSED=$(( CURRENT_TIME - ${START_TIME} ))
          echo "ELAPSED=$ELAPSED" >> $GITHUB_ENV
          echo "## Docker Image Summary" >> $GITHUB_STEP_SUMMARY
          echo "The following tags were pushed:" >> $GITHUB_STEP_SUMMARY
          echo "- \`${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- \`${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Docker image built and pushed successfully in ${ELAPSED}s." >> $GITHUB_STEP_SUMMARY


  check-development-backend-deployment:
    name: Check Backend Deployment
    runs-on: ubuntu-latest
    needs: [build-and-push]
    env:
      BACKEND_URL: ${{ vars.BACKEND_URL }}
      TIMEOUT: 300
      INTERVAL: 3
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get current version from package.json
        id: get_current_version
        run: echo "CURRENT_VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV

      - name: Check backend version consistency
        id: check_backend
        shell: bash
        run: |
          set +e
          START_TIME=$(date +%s)
          status=""
          while true; do
            CURRENT_TIME=$(date +%s)
            ELAPSED=$(( CURRENT_TIME - START_TIME ))
            if [ $ELAPSED -ge $TIMEOUT ]; then
              echo "ERROR: Condition not met after 5 minutes."
              echo "## :x: Development Deployment Failed" >> $GITHUB_STEP_SUMMARY
              echo "Unable to verify development deployment after 5 minutes." >> $GITHUB_STEP_SUMMARY
              status="failed"
              break
            fi

            response=$(curl -s "$BACKEND_URL" || echo "")
            if [ -z "$response" ]; then
              echo "Request failed: no response received. Retrying in $INTERVAL seconds..."
              sleep $INTERVAL
              continue
            fi
            version=$(echo "$response" | jq -r '.data.version.current' 2>/dev/null || echo "null")
            if [ -z "$version" ] || [ "$version" == "null" ]; then
              echo "Request failed: unable to parse version. Retrying in $INTERVAL seconds..."
              sleep $INTERVAL
              continue
            fi
            if [ "$version" != "$CURRENT_VERSION" ]; then
              echo "Version mismatch: expected $CURRENT_VERSION, got $version. Retrying in $INTERVAL seconds..."
              sleep $INTERVAL
              continue
            fi

            echo "Initial check passed with version $version. Performing additional 5 verifications..."

            all_checks_success=true
            for i in {1..5}; do
              response_check=$(curl -s "$BACKEND_URL" || echo "")
              if [ -z "$response_check" ]; then
                echo "Verification request $i failed: no response received."
                all_checks_success=false
                break
              fi
              version_check=$(echo "$response_check" | jq -r '.data.version.current' 2>/dev/null || echo "null")
              if [ -z "$version_check" ] || [ "$version_check" == "null" ]; then
                echo "Verification request $i failed: unable to parse version."
                all_checks_success=false
                break
              fi
              if [ "$version_check" != "$CURRENT_VERSION" ]; then
                echo "Verification request $i mismatch: expected $CURRENT_VERSION, got $version_check."
                all_checks_success=false
                break
              fi
            done

            if [ "$all_checks_success" = true ]; then
              echo "Success: All 5 verification requests returned the current version: $CURRENT_VERSION"
              echo "## :rocket: Development Deployment Success" >> $GITHUB_STEP_SUMMARY
              echo "Development deployment verified successfully in ${ELAPSED}s." >> $GITHUB_STEP_SUMMARY
              echo "- Backend URL: $BACKEND_URL" >> $GITHUB_STEP_SUMMARY
              echo "- Backend version: $CURRENT_VERSION" >> $GITHUB_STEP_SUMMARY
              status="success"
              break
            else
              echo "Verification failed. Continuing to poll..."
            fi

            sleep $INTERVAL
          done
          echo "status=$status" >> $GITHUB_OUTPUT
          if [ "$status" = "failed" ]; then
            exit 1
          fi
          echo "ELAPSED=$ELAPSED" >> $GITHUB_ENV